
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nyang_db?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: securus1234

  mybatis:
    config-location: classpath:mybatis-config.xml
    configuration:
      map-underscore-to-camel-case: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: cce6a069bc4d9aeb3ba98824d3ee428a
            redirect-uri: http://localhost:3000/oauth2/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id